spring:
  datasource:
    username: root
    password: 0102qazqaz
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop

  redis:
    host: localhost
    port: 6379
server:
  port: 8081
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
  consumer:
    group: order-group